#travis ci 
sudo: required
services:
  - docker

before_install:
  - docker build -t fcarbah/docker-react -f Dockerfile.dev .

script:
  #to end test suite  and exit to command line add the option: -- --coverage
  - docker run fcarbah/docker-react npm run test -- --coverage

#deploy to hosting -- we are using amazon elasticbeanstalk
deploy:
  #all of these come from amazon aws elastic beanstalk
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-184721162578"
  bucket_path: "docker-react" #same as app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
